### ISSUE TITLE
How to execute the convert-spread3.sh?

### ISSUE THREAD

**Issue by virologist** [VirologyCharite/convert-spread3#1]
Hi, Terry

Recently, I am trying to use SpreaD3 to interpret the phylogeographic diffusion of flu. I meet as same as the error described in https://github.com/phylogeography/SpreaD3/issues/32. I struggled here for many hours. Then I found your solutions. Very nice. It's relief me. However, I don't know how to use this .sh. Could you please give me some clues? 
I try PowerShell on my win 10 and WSL. Neither of them works well. 
I put the snapshots of the errors I take.
![image](https://user-images.githubusercontent.com/54756814/83738731-41071380-a687-11ea-9f74-d0042fbcae60.png)
![image](https://user-images.githubusercontent.com/54756814/83738760-4bc1a880-a687-11ea-99aa-9409488998ec.png)
![image](https://user-images.githubusercontent.com/54756814/83738778-511ef300-a687-11ea-91ab-d17635d94f05.png)
Thanks a lot!

Best regards,
Yan

**Comment by terrycojones** [comment]
Hi Yan.  I don't use windows, so this may not work. Using WSL is the best option. Try this:

```sh
$ mkdir /tmp
$ apt-get install awk sed
```

You may need to put `sudo` before that final command, but I don't know if that exists or is needed on windows. Then try re-running.

**Comment by virologist** [comment]
Thank you very much, Terry. I made it.

```
$ mkdir tmp
$ sudo apt-get install awk sed
$ bash convert-spread3.sh
```

**Comment by terrycojones** [comment]
Great - good on you for digging into this and getting it all the way fixed on your system! That's really nice to hear and you are in a minority! :-) Best of luck with your work.

**Comment by virologist** [comment]
Thank you very much!
Without your code and tutorial, I can’t move forward a single step.

Best regard
